### ISSUE TITLE
Is it possible to enable touch screen and upper buttons of the trackpad?

### ISSUE THREAD

**Issue by KenWuqianghao** [SkyrilHD/Dell-Exx50-Hackintosh#13]
Is it possible to enable the touch screen and upper buttons of the trackpad?

**Comment by SkyrilHD** [comment]
For touchscreen (not tested yet; maybe you can provide feedback), you need to enable these lines in config:

https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/ddd8a6bf40cab1762a3b3061ff2ae5a32e49d1ce/OpenCore/EFI/OC/config.plist#L854
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/ddd8a6bf40cab1762a3b3061ff2ae5a32e49d1ce/OpenCore/EFI/OC/config.plist#L872
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/ddd8a6bf40cab1762a3b3061ff2ae5a32e49d1ce/OpenCore/EFI/OC/config.plist#L890
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/ddd8a6bf40cab1762a3b3061ff2ae5a32e49d1ce/OpenCore/EFI/OC/config.plist#L908
https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/blob/ddd8a6bf40cab1762a3b3061ff2ae5a32e49d1ce/OpenCore/EFI/OC/config.plist#L926

But I don't think you can enable the upper buttons due to the limitation of the VoodooPS2 kext...

**Comment by KenWuqianghao** [comment]
Works well! Thank you!
