### ISSUE TITLE
VGA Port is not working

### ISSUE THREAD

**Issue by quynkk5** [SkyrilHD/Dell-Exx50-Hackintosh#21]
I have Dell Latitude E5550 and I applied your EFI. 
Almost working, but VGA Port seems to be not work, HDMI is working well when i'm adding framebuffer patches.
Can you help me for enabling VGA Port?
My edited EFI (added rename EH01, SSDT-XOSI, recoded kext voodoops2 for smooth with 2-3-4 fingures,...): https://drive.google.com/file/d/1ZFu8fpYE5WyVb5Ejeu_sNa3Za_LJUVwY/view?usp=sharing

**Comment by SkyrilHD** [comment]
On E7250 (which I own) there is no VGA port, so I couldn't investigate time to add VGA support. But in WhateverGreen doc, it mentions some stuff for VGA which I can't test. You can find it here: [Link](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#vga-support)

> In most cases with Intel Skylake and newer it works by default.

Our system is Broadwell (a generation before Skylake), so it doesn't work by default. 

> For Ivy Bridge and possibly other generations there are the options to patch your connectors with the following:
06020000 02000000 30000000 // Option 1
06020000 01000000 30000000 // Option 2

This patch has higher chances to work on Ivy Bridge (3rd gen), so I doubt it would work on Broadwell. But I suggest to try out the patches mentioned above.

> On OS X 10.8.2 and newer it is impossible to have VGA on Ivy Bridge systems.

Doesn't matter for us, since we use Broadwell. 

> Hot-plugging VGA usually does not work.

Make sure, you plugged the VGA cable in before you boot to macOS.

> In case this doesn't help - there are no other known solutions at this time.

So if the patches don't work, I doubt we can get it working and I will close the issue as 'wontfix'
