### ISSUE TITLE
Volume hash Mismatch error Monterey 12.3.1

### ISSUE THREAD

**Issue by kaem-e** [SkyrilHD/Dell-Exx50-Hackintosh#50]
MacOS seems to bug out at random prompting the following notification
 ![Screenshot 2022-05-17 at 8 48 12 AM](https://user-images.githubusercontent.com/46230985/168725595-50762c60-f834-4189-ba20-f274b32e72b8.png)
after which the screen goes black and the menubar grey. Things like mission control, dock, alt tab and switching workspaces also stops working 
![Screenshot 2022-05-17 at 8 55 07 AM](https://user-images.githubusercontent.com/46230985/168725581-d90e846d-b07a-437b-9e4c-e2f19e963b2b.png)

I did find a workaround to just type sudo purge in the terminal which sometimes fixes this issue but not all the time at which point I need to restart the system. This is after a fresh install and across two different suds so I don't believe this has something to do with the install or hard drive itself

Laptop: Latitude E5450
efi-release: 0.7.9 (latest release in this repo at the time)
Config.plist: [config.plist.txt](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/files/8705052/config.plist.txt) (remane from config.plist.txt to .plist)

**Comment by SkyrilHD** [comment]
Sadly, I cannot fix it as it is not EFI related. Apple needs to fix the issue themselves. But I also encountered this issue however reduced since 12.3. I could mostly trigger it by opening Xcode while under load. Seems like stressing macOS causes some crashes? Another cause could be bluetoothd crashing due to the known issues (Bluetooth broken after sleep) and needs to be killall'd after every wake. The command is `sudo killall -9 BlueTool bluetoothd`

Check if the issue gets better by using this command after every sleep.

**Comment by kaem-e** [comment]
Yeah that seems to reduce the frequency by which this happens,
