### ISSUE TITLE
Graphical glitches E5550

### ISSUE THREAD

**Issue by hickorysb** [SkyrilHD/Dell-Exx50-Hackintosh#7]
I had a graphical glitch where there would be a bunch of lines across the screen and it would horizontally duplicate the middle of the screen in columns. I fixed this by turning on legacy option ROMs in the BIOS. I've got a Hackintosh now that is almost 100% functioning. The only things not working are the fingerprint reader and smart card slot, but those are to be expected. Thank you for this amazing guide/EFI.

Edit: Even though I had legacy option ROMs on, I still booted UEFI.

**Comment by SkyrilHD** [comment]
Glad to hear it works well. I'm assuming you have 1080p because my 768p display doesn't have this problem. emrah7celik posted a workaround that you can try. https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/discussions/6
You could try providing feedback. I could add it to README so that everyone can see it. 

But yeah, fingerprint and smart card do not work..

**Comment by hickorysb** [comment]
I no longer have the graphical issue. Like I said it was a simple BIOS option. The WiFi card that the laptop came with is also working support well, Intel AC 9765. Had to change the EFI just a bit though.

**Comment by SkyrilHD** [comment]
Will add that in README. Thanks for mentioning.

For people who want to use pure UEFI, an EDID patch needs to be added.
