### ISSUE TITLE
Dell Latitude E5550 Not Recognising SD Card

### ISSUE THREAD

**Issue by Bill-Joe-Tech** [SkyrilHD/Dell-Exx50-Hackintosh#72]
Hello I am having problems with my Dell (Latitude E5550) Hackintosh recognising the SD card. Using Linux/Windows, the SD card works. Running Ventura 13.4.

Using `diskutil list` does not show...

**Comment by tommasobab** [comment]
> Hello I am having problems with my Dell (Latitude E5550) Hackintosh recognising the SD card. Using Linux/Windows, the SD card works. Running Ventura 13.4.
> 
> Using `diskutil list` does not show...

Recent MacBooks doesn't have a SD slot anymore

Can you please send me the efi, I really need that.

**Comment by Bill-Joe-Tech** [comment]
Uploaded as 7z as zip was too big to upload here

**Comment by Bill-Joe-Tech** [comment]
[Ventura OC E5550.zip](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/files/12389198/Ventura.OC.E5550.zip)
1. Rename extension `.7z`
2. Extract with 7zip (had to compress with 7z as GitHub imposes file limit uploads to 25 MB).

**Comment by SkyrilHD** [comment]
Some SD Cards will not work because we use Apple's native SD card driver. We are spoofing our O2 Micro Card Reader to a BCM57765/57785 Card Reader, which, luckily for us, works. The downside, however, is that newer cards are not recognised (at least according to my test results). Sadly, there is nothing I can do about it, so it will be a 'won't fix' on my end.
